"""created 'payment' table

Revision ID: 05f75ec975ac
Revises: 
Create Date: 2022-12-18 23:13:55.926859

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils

# revision identifiers, used by Alembic.
revision = '05f75ec975ac'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    PAYMENT_STATE = [
        ("Оплачено", "Оплачено"),
        ("В ожидании", "В ожидании"),
        ("Не aктуально", "Не aктуально"),
    ]

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payments',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_paid', sqlalchemy_utils.types.choice.ChoiceType(PAYMENT_STATE), nullable=True),
    sa.Column('order_id', sa.VARCHAR(length=50), nullable=False),
    sa.Column('order_link', sa.String(), nullable=False),
    sa.Column('creator_data', sa.VARCHAR(length=100), nullable=False),
    sa.Column('lesson_type', sa.VARCHAR(length=20), nullable=False),
    sa.Column('parents_name', sa.VARCHAR(length=50), nullable=False),
    sa.Column('description', sa.VARCHAR(length=512), nullable=True),
    sa.Column('amount', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payments')
    # ### end Alembic commands ###
