"""update

Revision ID: 1dff269bd65a
Revises: ec698557e0ae
Create Date: 2023-01-07 18:41:33.058155

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy_utils.types import ChoiceType


# revision identifiers, used by Alembic.
revision = '1dff269bd65a'
down_revision = 'ec698557e0ae'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
