"""update!

Revision ID: 5e9d3c12718f
Revises: decde9e7edc6
Create Date: 2023-01-11 22:19:07.454450

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy_utils.types import ChoiceType


# revision identifiers, used by Alembic.
revision = '5e9d3c12718f'
down_revision = 'decde9e7edc6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pushes', sa.Column('sheet', sa.BigInteger(), nullable=True))
    op.drop_column('pushes', 'limit')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pushes', sa.Column('limit', sa.BIGINT(), autoincrement=False, nullable=True))
    op.drop_column('pushes', 'sheet')
    # ### end Alembic commands ###
