"""update order fileds

Revision ID: 62af517fd34c
Revises: 05f75ec975ac
Create Date: 2022-12-20 01:21:56.843658

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy_utils.types import ChoiceType


# revision identifiers, used by Alembic.
revision = '62af517fd34c'
down_revision = '05f75ec975ac'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('payments', 'order_id',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('payments', 'order_link',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('payments', 'order_link',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('payments', 'order_id',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    # ### end Alembic commands ###
