"""update

Revision ID: decde9e7edc6
Revises: 1dff269bd65a
Create Date: 2023-01-07 18:41:55.776785

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy_utils.types import ChoiceType


# revision identifiers, used by Alembic.
revision = 'decde9e7edc6'
down_revision = '1dff269bd65a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
