"""update

Revision ID: ec698557e0ae
Revises: ff0eff84fbc1
Create Date: 2023-01-07 18:39:51.673350

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy_utils.types import ChoiceType


# revision identifiers, used by Alembic.
revision = 'ec698557e0ae'
down_revision = 'ff0eff84fbc1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
