"""update

Revision ID: ff0eff84fbc1
Revises: 7094e1093db7
Create Date: 2023-01-07 18:38:35.626746

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy_utils.types import ChoiceType


# revision identifiers, used by Alembic.
revision = 'ff0eff84fbc1'
down_revision = '7094e1093db7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('creator_username', sa.BigInteger(), nullable=True))
    op.add_column('payments', sa.Column('creator_telegram_id', sa.VARCHAR(length=100), nullable=True))
    op.drop_column('payments', 'creator_data')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('creator_data', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.drop_column('payments', 'creator_telegram_id')
    op.drop_column('payments', 'creator_username')
    # ### end Alembic commands ###
